version: 2

jobs:
  build:
    working_directory: ~/tulle
    docker:
      - image: circleci/ruby:2.6.5
        environment:
          APP_ENV: test
    steps:
      - checkout

      - run:
          name: Bundle install dependencies.
          command: bundle install --path vendor/bundle

      - type: shell
        name: Run linter.
        command: bundle exec rubocop

      - type: shell
        name: Run tests.
        command: bundle exec rspec

